#!/usr/bin/env node
/**
 * OmbRouter CLI
 *
 * Standalone proxy for deployed setups where the proxy needs to survive gateway restarts.
 *
 * Usage (from repo: npm run build, then):
 *   node dist/cli.js              # Start standalone proxy
 *   node dist/cli.js --version    # Show version
 *   node dist/cli.js --port 8402  # Custom port
 *
 * If the ombrouter bin is on PATH (e.g. npm link):
 *   ombrouter
 *
 * For production deployments, use with PM2, e.g.:
 *   pm2 start "node dist/cli.js" --name ombrouter --cwd /path/to/OmbRouter
 */

import { startProxy, getProxyPort } from "./proxy.js";
import type { UpstreamMode } from "./proxy/upstream-transport.js";
import type { MoonPayChain } from "./proxy/moonpay-upstream-transport.js";
import { VERSION } from "./version.js";
import {
  resolveOrGenerateWalletKey,
  resolvePaymentChain,
  recoverWalletFromMnemonic,
  savePaymentChain,
} from "./auth.js";
import { getSolanaAddress } from "./wallet.js";
import { generateReport } from "./report.js";
import { formatRecentLogs } from "./stats.js";
import { runDoctor } from "./doctor.js";
import { PARTNER_SERVICES } from "./partners/index.js";

function printHelp(): void {
  console.log(`
OmbRouter v${VERSION} - Smart LLM Router

Usage:
  ombrouter [options]
  ombrouter status                    # Live proxy status (wallet, balance, chain)
  ombrouter wallet                    # Wallet details + balance
  ombrouter models                    # List available models
  ombrouter stats [--days <n>]       # Usage stats (default: 7 days)
  ombrouter doctor [opus] [question]
  ombrouter partners [test]
  ombrouter report [daily|weekly|monthly] [--json]
  ombrouter logs [--days <n>]

Options:
  --version, -v     Show version number
  --help, -h        Show this help message
  --port <number>   Port to listen on (default: ${getProxyPort()})
  --upstream-mode x402|apiKey|moonpay  Transport (default x402; env OMBROUTER_UPSTREAM_MODE)
  --upstream-api-base <url>   apiKey: required. moonpay: optional x402 API base (default BlockRun)
  --upstream-api-key <key>    Required for apiKey (or OMBROUTER_UPSTREAM_API_KEY)
  --moonpay-wallet <name>     Required for moonpay (or OMBROUTER_MOONPAY_WALLET)
  --moonpay-chain <chain>     base|solana|ethereum|... for moonpay payment (default base)
  --moonpay-cli <path>        Path to mp binary (default: mp)
  --apikey-aux-routes         apiKey: enable Bearer forward for images/audio/partner (or env OMBROUTER_APIKEY_AUX_ROUTES)
  --no-apikey-aux-routes      apiKey: disable auxiliary routes even if env is set

Query Commands (talk to running proxy on localhost:${getProxyPort()}):
  status            Proxy status: wallet, balance, payment chain
  wallet            Wallet addresses + USDC balance
  models            List all available models with pricing
  stats             Usage breakdown: requests, cost, top models
  stats --days 14   Custom time range (max 30 days)
  cache             Response cache stats (hit rate, size)

Management Commands:
  doctor            AI-powered diagnostics (default: Sonnet ~$0.003)
  doctor opus       Use Opus for deeper analysis (~$0.01)
  logs              Per-request breakdown: model, cost, latency, status
  logs --days 7     Show last 7 days of requests (default: 1 day)
  partners          List available partner APIs with pricing
  partners test     Test partner API endpoints (expect 402 = alive)
  wallet recover    Restore wallet.key from mnemonic (if generated by OmbRouter)
  chain solana      Switch to Solana (persists)
  chain base        Switch to Base EVM (persists)

Environment Variables:
  BLOCKRUN_WALLET_KEY          Private key for x402 payments (auto-generated if not set)
  BLOCKRUN_PROXY_PORT          Default proxy port (default: 8402)
  OMBROUTER_UPSTREAM_MODE      x402 (default) or apiKey
  OMBROUTER_UPSTREAM_API_BASE  Base URL for apiKey mode (e.g. https://api.openai.com/v1)
  OMBROUTER_UPSTREAM_API_KEY   API key for apiKey mode
  OMBROUTER_APIKEY_AUX_ROUTES  apiKey: true/1/yes to forward images/audio/partner to upstream (Bearer)
  OMBROUTER_MOONPAY_WALLET     Wallet name for moonpay mode (with --upstream-mode moonpay)

For more info: see the OmbRouter README in this repository.
`);
}

/** Query the running proxy HTTP API */
async function queryProxy(path: string, port: number): Promise<unknown> {
  const res = await fetch(`http://127.0.0.1:${port}${path}`);
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
  return res.json();
}

async function cmdStatus(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/health?full=true", port)) as Record<string, unknown>;
    console.log(`\nOmbRouter Status (port ${port})\n`);
    console.log(`  Status:        ${data.status}`);
    console.log(`  Payment Chain: ${data.paymentChain}`);
    console.log(`  EVM Wallet:    ${data.wallet}`);
    if (data.solana) console.log(`  Solana Wallet: ${data.solana}`);
    console.log(`  Balance:       ${data.balance ?? "unknown"}`);
    if (data.isLow) console.log(`  ⚠ Balance is low`);
    if (data.isEmpty) console.log(`  ⚠ Balance is empty — using free models`);
    if (data.upstreamProxy) console.log(`  Upstream Proxy: ${data.upstreamProxy}`);
    console.log();
  } catch {
    console.error(`✗ Cannot connect to OmbRouter on port ${port}`);
    console.error(`  Is the proxy running? Start with: node dist/cli.js (or: ombrouter)`);
    process.exit(1);
  }
}

async function cmdWallet(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/health?full=true", port)) as Record<string, unknown>;
    console.log(`\nOmbRouter Wallet\n`);
    console.log(`  Payment Chain: ${data.paymentChain}`);
    console.log();
    console.log(`  Base (EVM):`);
    console.log(`    Address: ${data.wallet}`);
    console.log(`    Fund:    https://basescan.org/address/${data.wallet}`);
    if (data.solana) {
      console.log();
      console.log(`  Solana:`);
      console.log(`    Address: ${data.solana}`);
      console.log(`    Fund:    https://solscan.io/account/${data.solana}`);
    }
    console.log();
    console.log(`  Balance: ${data.balance ?? "unknown"} (USDC)`);
    if (data.isEmpty) console.log(`  ⚠ Empty — fund wallet or use free models`);
    console.log();
  } catch {
    console.error(`✗ Cannot connect to OmbRouter on port ${port}`);
    process.exit(1);
  }
}

async function cmdModels(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/v1/models", port)) as {
      data: Array<{ id: string; owned_by?: string }>;
    };
    console.log(`\nAvailable Models (${data.data.length})\n`);

    // Group by provider
    const groups = new Map<string, string[]>();
    for (const m of data.data) {
      const provider = m.id.includes("/") ? m.id.split("/")[0] : "blockrun";
      if (!groups.has(provider)) groups.set(provider, []);
      groups.get(provider)!.push(m.id);
    }

    for (const [provider, models] of groups) {
      console.log(`  ${provider} (${models.length}):`);
      for (const id of models) {
        console.log(`    ${id}`);
      }
      console.log();
    }
  } catch {
    console.error(`✗ Cannot connect to OmbRouter on port ${port}`);
    process.exit(1);
  }
}

async function cmdStats(port: number, days: number): Promise<void> {
  try {
    const data = (await queryProxy(`/stats?days=${days}`, port)) as Record<string, unknown>;
    const stats = data as {
      totalRequests?: number;
      totalCostUsd?: number;
      savedUsd?: number;
      savingsPercent?: number;
      topModels?: Array<{ model: string; requests: number; costUsd: number }>;
    };

    console.log(`\nUsage Stats (last ${days} days)\n`);
    console.log(`  Requests: ${stats.totalRequests ?? 0}`);
    console.log(`  Cost:     $${(stats.totalCostUsd ?? 0).toFixed(4)}`);
    if (stats.savedUsd) {
      console.log(
        `  Saved:    $${stats.savedUsd.toFixed(4)} (${stats.savingsPercent?.toFixed(0) ?? 0}% vs Opus)`,
      );
    }

    if (stats.topModels && stats.topModels.length > 0) {
      console.log();
      console.log(`  Top Models:`);
      for (const m of stats.topModels.slice(0, 10)) {
        console.log(
          `    ${m.model.padEnd(40)} ${String(m.requests).padStart(5)} reqs  $${m.costUsd.toFixed(4)}`,
        );
      }
    }
    console.log();
  } catch {
    console.error(`✗ Cannot connect to OmbRouter on port ${port}`);
    process.exit(1);
  }
}

async function cmdCache(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/cache", port)) as Record<string, unknown>;
    console.log(`\nCache Stats\n`);
    for (const [key, value] of Object.entries(data)) {
      console.log(`  ${key}: ${JSON.stringify(value)}`);
    }
    console.log();
  } catch {
    console.error(`✗ Cannot connect to OmbRouter on port ${port}`);
    process.exit(1);
  }
}

function parseArgs(args: string[]): {
  version: boolean;
  help: boolean;
  doctor: boolean;
  logs: boolean;
  logsDays: number;
  partners: boolean;
  partnersTest: boolean;
  report: boolean;
  reportPeriod: "daily" | "weekly" | "monthly";
  reportJson: boolean;
  walletRecover: boolean;
  chain?: "solana" | "base";
  port?: number;
  // Query commands
  queryStatus: boolean;
  queryWallet: boolean;
  queryModels: boolean;
  queryStats: boolean;
  queryStatsDays: number;
  queryCache: boolean;
  upstreamMode?: UpstreamMode;
  upstreamApiBase?: string;
  upstreamApiKey?: string;
  moonpayWallet?: string;
  moonpayPaymentChain?: MoonPayChain;
  moonpayCliPath?: string;
  apikeyAuxRoutes?: boolean;
} {
  const result = {
    version: false,
    help: false,
    doctor: false,
    logs: false,
    logsDays: 1,
    partners: false,
    partnersTest: false,
    report: false,
    reportPeriod: "daily" as "daily" | "weekly" | "monthly",
    reportJson: false,
    walletRecover: false,
    chain: undefined as "solana" | "base" | undefined,
    port: undefined as number | undefined,
    queryStatus: false,
    queryWallet: false,
    queryModels: false,
    queryStats: false,
    queryStatsDays: 7,
    queryCache: false,
    upstreamMode: undefined as UpstreamMode | undefined,
    upstreamApiBase: undefined as string | undefined,
    upstreamApiKey: undefined as string | undefined,
    moonpayWallet: undefined as string | undefined,
    moonpayPaymentChain: undefined as MoonPayChain | undefined,
    moonpayCliPath: undefined as string | undefined,
    apikeyAuxRoutes: undefined as boolean | undefined,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--version" || arg === "-v") {
      result.version = true;
    } else if (arg === "--help" || arg === "-h") {
      result.help = true;
    } else if (arg === "status") {
      result.queryStatus = true;
    } else if (arg === "models") {
      result.queryModels = true;
    } else if (arg === "stats") {
      result.queryStats = true;
      if (args[i + 1] === "--days" && args[i + 2]) {
        result.queryStatsDays = Math.min(parseInt(args[i + 2], 10) || 7, 30);
        i += 2;
      }
    } else if (arg === "cache") {
      result.queryCache = true;
    } else if (arg === "doctor" || arg === "--doctor") {
      result.doctor = true;
    } else if (arg === "logs") {
      result.logs = true;
      if (args[i + 1] === "--days" && args[i + 2]) {
        result.logsDays = parseInt(args[i + 2], 10) || 1;
        i += 2;
      }
    } else if (arg === "partners") {
      result.partners = true;
      if (args[i + 1] === "test") {
        result.partnersTest = true;
        i++;
      }
    } else if (arg === "report") {
      result.report = true;
      const next = args[i + 1];
      if (next && ["daily", "weekly", "monthly"].includes(next)) {
        result.reportPeriod = next as "daily" | "weekly" | "monthly";
        i++;
        if (args[i + 1] === "--json") {
          result.reportJson = true;
          i++;
        }
      } else if (next === "--json") {
        result.reportJson = true;
        i++;
      }
    } else if (arg === "wallet") {
      if (args[i + 1] === "recover") {
        result.walletRecover = true;
        i++;
      } else if (args[i + 1] === "solana" || args[i + 1] === "base") {
        result.chain = args[i + 1] as "solana" | "base";
        i++;
      } else {
        result.queryWallet = true;
      }
    } else if (
      (arg === "chain" || arg === "/wallet") &&
      (args[i + 1] === "solana" || args[i + 1] === "base")
    ) {
      result.chain = args[i + 1] as "solana" | "base";
      i++;
    } else if (arg === "--port" && args[i + 1]) {
      result.port = parseInt(args[i + 1], 10);
      i++;
    } else if (arg === "--upstream-mode" && args[i + 1]) {
      const m = args[i + 1];
      if (m === "apiKey" || m === "x402" || m === "moonpay") result.upstreamMode = m;
      i++;
    } else if (arg === "--upstream-api-base" && args[i + 1]) {
      result.upstreamApiBase = args[i + 1];
      i++;
    } else if (arg === "--upstream-api-key" && args[i + 1]) {
      result.upstreamApiKey = args[i + 1];
      i++;
    } else if (arg === "--moonpay-wallet" && args[i + 1]) {
      result.moonpayWallet = args[i + 1];
      i++;
    } else if (arg === "--moonpay-chain" && args[i + 1]) {
      const c = args[i + 1] as MoonPayChain;
      if (
        ["solana", "base", "ethereum", "arbitrum", "polygon", "optimism"].includes(c)
      ) {
        result.moonpayPaymentChain = c;
      }
      i++;
    } else if (arg === "--moonpay-cli" && args[i + 1]) {
      result.moonpayCliPath = args[i + 1];
      i++;
    } else if (arg === "--apikey-aux-routes") {
      result.apikeyAuxRoutes = true;
    } else if (arg === "--no-apikey-aux-routes") {
      result.apikeyAuxRoutes = false;
    }
  }

  return result;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  if (args.version) {
    console.log(VERSION);
    process.exit(0);
  }

  if (args.help) {
    printHelp();
    process.exit(0);
  }

  // Query commands — talk to running proxy
  const queryPort = args.port ?? getProxyPort();

  if (args.queryStatus) {
    await cmdStatus(queryPort);
    process.exit(0);
  }
  if (args.queryWallet) {
    await cmdWallet(queryPort);
    process.exit(0);
  }
  if (args.queryModels) {
    await cmdModels(queryPort);
    process.exit(0);
  }
  if (args.queryStats) {
    await cmdStats(queryPort, args.queryStatsDays);
    process.exit(0);
  }
  if (args.queryCache) {
    await cmdCache(queryPort);
    process.exit(0);
  }

  if (args.doctor) {
    // Parse: doctor [opus|sonnet] [question...]
    const rawArgs = process.argv.slice(2);
    const doctorIndex = rawArgs.findIndex((a) => a === "doctor" || a === "--doctor");
    const afterDoctor = rawArgs.slice(doctorIndex + 1);

    // Check if first arg is model selection
    let model: "sonnet" | "opus" = "sonnet"; // default to cheaper
    let questionArgs = afterDoctor;

    if (afterDoctor[0] === "opus") {
      model = "opus";
      questionArgs = afterDoctor.slice(1);
    } else if (afterDoctor[0] === "sonnet") {
      model = "sonnet";
      questionArgs = afterDoctor.slice(1);
    }

    const userQuestion = questionArgs.join(" ").trim() || undefined;
    await runDoctor(userQuestion, model);
    process.exit(0);
  }

  if (args.logs) {
    const output = await formatRecentLogs(args.logsDays);
    console.log(output);
    process.exit(0);
  }

  if (args.partners) {
    if (PARTNER_SERVICES.length === 0) {
      console.log("No partner APIs available.");
      process.exit(0);
    }

    console.log(`\nOmbRouter Partner APIs (v${VERSION})\n`);

    for (const svc of PARTNER_SERVICES) {
      console.log(`  ${svc.name} (${svc.partner})`);
      console.log(`    ${svc.description}`);
      console.log(`    Tool:    blockrun_${svc.id}`);
      console.log(`    Method:  ${svc.method} /v1${svc.proxyPath}`);
      console.log(
        `    Pricing: ${svc.pricing.perUnit} per ${svc.pricing.unit} (min ${svc.pricing.minimum}, max ${svc.pricing.maximum})`,
      );
      console.log();
    }

    if (args.partnersTest) {
      console.log("Testing partner endpoints...\n");
      const apiBase = "https://blockrun.ai/api";
      for (const svc of PARTNER_SERVICES) {
        const url = `${apiBase}/v1${svc.proxyPath}`;
        try {
          const response = await fetch(url, { method: "GET" });
          const status = response.status;
          const ok = status === 402 ? "alive (402 = payment required)" : `status ${status}`;
          console.log(`  ${svc.id}: ${ok}`);
        } catch (err) {
          console.log(`  ${svc.id}: error - ${err instanceof Error ? err.message : String(err)}`);
        }
      }
      console.log();
    }

    process.exit(0);
  }

  if (args.walletRecover) {
    await recoverWalletFromMnemonic();
    process.exit(0);
  }

  if (args.chain) {
    const targetChain = args.chain;

    if (targetChain === "solana") {
      // Ensure Solana wallet is set up (mnemonic → keypair)
      const { existsSync } = await import("fs");
      const { MNEMONIC_FILE, setupSolana } = await import("./auth.js");
      const { deriveSolanaKeyBytes, getSolanaAddress } = await import("./wallet.js");

      let solanaAddr: string;
      if (existsSync(MNEMONIC_FILE)) {
        // Already set up — derive address from existing mnemonic
        const { readFileSync } = await import("fs");
        const mnemonic = readFileSync(MNEMONIC_FILE, "utf8").trim();
        const keyBytes = deriveSolanaKeyBytes(mnemonic);
        solanaAddr = await getSolanaAddress(keyBytes);
        console.log(`[OmbRouter] Solana wallet already set up.`);
      } else {
        // First time — generate mnemonic + keypair
        console.log(`[OmbRouter] Setting up Solana wallet...`);
        const { solanaPrivateKeyBytes } = await setupSolana();
        solanaAddr = await getSolanaAddress(solanaPrivateKeyBytes);
        console.log(`[OmbRouter] Solana wallet created.`);
        console.log(`[OmbRouter] ⚠  Back up your mnemonic: ${MNEMONIC_FILE}`);
      }

      await savePaymentChain("solana");
      console.log(`[OmbRouter] Payment chain → Solana`);
      console.log(`[OmbRouter] Solana address : ${solanaAddr}`);
      console.log(`[OmbRouter] Fund USDC at   : https://solscan.io/account/${solanaAddr}`);
    } else {
      await savePaymentChain("base");
      console.log(`[OmbRouter] Payment chain → Base (EVM)`);
    }

    console.log(
      `[OmbRouter] Restart gateway to apply: systemctl --user restart openclaw-gateway.service`,
    );
    console.log(`[OmbRouter]   or: openclaw gateway restart`);
    process.exit(0);
  }

  if (args.report) {
    const report = await generateReport(args.reportPeriod, args.reportJson);
    console.log(report);
    process.exit(0);
  }

  const envMode = process.env.OMBROUTER_UPSTREAM_MODE?.trim();
  const upstreamMode: UpstreamMode =
    args.upstreamMode ??
    (envMode === "apiKey"
      ? "apiKey"
      : envMode === "moonpay"
        ? "moonpay"
        : envMode === "x402"
          ? "x402"
          : "x402");

  const upstreamApiBase =
    args.upstreamApiBase?.trim() || process.env.OMBROUTER_UPSTREAM_API_BASE?.trim();
  const upstreamApiKey =
    args.upstreamApiKey?.trim() || process.env.OMBROUTER_UPSTREAM_API_KEY?.trim();
  const moonpayWallet =
    args.moonpayWallet?.trim() || process.env.OMBROUTER_MOONPAY_WALLET?.trim();

  let proxy: Awaited<ReturnType<typeof startProxy>>;

  if (upstreamMode === "apiKey") {
    if (!upstreamApiKey) {
      console.error(`[OmbRouter] apiKey mode requires --upstream-api-key or OMBROUTER_UPSTREAM_API_KEY`);
      process.exit(1);
    }
    if (!upstreamApiBase) {
      console.error(
        `[OmbRouter] apiKey mode requires --upstream-api-base or OMBROUTER_UPSTREAM_API_BASE`,
      );
      process.exit(1);
    }
    console.log(`[OmbRouter] Upstream: apiKey → ${upstreamApiBase}`);
    proxy = await startProxy({
      upstreamMode: "apiKey",
      upstreamApiKey,
      apiBase: upstreamApiBase,
      apiKeyAllowAuxRoutes: args.apikeyAuxRoutes,
      port: args.port,
      onReady: (port) => {
        console.log(`[OmbRouter] v${VERSION} | Proxy listening on http://127.0.0.1:${port}`);
        console.log(`[OmbRouter] Health check: http://127.0.0.1:${port}/health`);
      },
      onError: (error) => {
        console.error(`[OmbRouter] Error: ${error.message}`);
      },
      onRouted: (decision) => {
        const cost = decision.costEstimate.toFixed(4);
        const saved = (decision.savings * 100).toFixed(0);
        console.log(`[OmbRouter] [${decision.tier}] ${decision.model} $${cost} (saved ${saved}%)`);
      },
      onLowBalance: (info) => {
        console.warn(`[OmbRouter] Low balance: ${info.balanceUSD}. Fund: ${info.walletAddress}`);
      },
      onInsufficientFunds: (info) => {
        console.error(
          `[OmbRouter] Insufficient funds. Balance: ${info.balanceUSD}, Need: ${info.requiredUSD}`,
        );
        console.error(`[OmbRouter] Need help? Run: ombrouter doctor (or: node dist/cli.js doctor)`);
      },
    });
    console.log(`[OmbRouter] Ready (apiKey upstream) — Ctrl+C to stop`);
  } else if (upstreamMode === "moonpay") {
    if (!moonpayWallet) {
      console.error(
        `[OmbRouter] moonpay mode requires --moonpay-wallet or OMBROUTER_MOONPAY_WALLET`,
      );
      process.exit(1);
    }
    console.log(
      `[OmbRouter] Upstream: MoonPay CLI (mp x402 request), wallet "${moonpayWallet}" — ensure \`mp login\` is done`,
    );
    proxy = await startProxy({
      upstreamMode: "moonpay",
      moonpayWallet,
      apiBase: upstreamApiBase || undefined,
      moonpayPaymentChain: args.moonpayPaymentChain ?? "base",
      moonpayCliPath: args.moonpayCliPath,
      port: args.port,
      onReady: (port) => {
        console.log(`[OmbRouter] v${VERSION} | Proxy listening on http://127.0.0.1:${port}`);
        console.log(`[OmbRouter] Health check: http://127.0.0.1:${port}/health`);
      },
      onError: (error) => {
        console.error(`[OmbRouter] Error: ${error.message}`);
      },
      onRouted: (decision) => {
        const cost = decision.costEstimate.toFixed(4);
        const saved = (decision.savings * 100).toFixed(0);
        console.log(`[OmbRouter] [${decision.tier}] ${decision.model} $${cost} (saved ${saved}%)`);
      },
      onLowBalance: (info) => {
        console.warn(`[OmbRouter] Low balance: ${info.balanceUSD}. Fund: ${info.walletAddress}`);
      },
      onInsufficientFunds: (info) => {
        console.error(
          `[OmbRouter] Insufficient funds. Balance: ${info.balanceUSD}, Need: ${info.requiredUSD}`,
        );
        console.error(`[OmbRouter] Need help? Run: ombrouter doctor (or: node dist/cli.js doctor)`);
      },
    });
    console.log(`[OmbRouter] Ready (MoonPay upstream) — Ctrl+C to stop`);
  } else {
    const wallet = await resolveOrGenerateWalletKey();

    if (wallet.source === "generated") {
      console.log(`[OmbRouter] Generated new wallet: ${wallet.address}`);
    } else if (wallet.source === "saved") {
      console.log(`[OmbRouter] Using saved wallet: ${wallet.address}`);
    } else if (wallet.source === "config") {
      console.log(`[OmbRouter] Using wallet from plugin config: ${wallet.address}`);
    } else {
      console.log(`[OmbRouter] Using wallet from BLOCKRUN_WALLET_KEY: ${wallet.address}`);
    }

    if (wallet.solanaPrivateKeyBytes) {
      try {
        const solAddr = await getSolanaAddress(wallet.solanaPrivateKeyBytes);
        console.log(`[OmbRouter] Solana address: ${solAddr}`);
      } catch {
        // Non-fatal
      }
    }

    proxy = await startProxy({
      wallet,
      port: args.port,
      onReady: (port) => {
        console.log(`[OmbRouter] v${VERSION} | Proxy listening on http://127.0.0.1:${port}`);
        console.log(`[OmbRouter] Health check: http://127.0.0.1:${port}/health`);
      },
      onError: (error) => {
        console.error(`[OmbRouter] Error: ${error.message}`);
      },
      onRouted: (decision) => {
        const cost = decision.costEstimate.toFixed(4);
        const saved = (decision.savings * 100).toFixed(0);
        console.log(`[OmbRouter] [${decision.tier}] ${decision.model} $${cost} (saved ${saved}%)`);
      },
      onLowBalance: (info) => {
        console.warn(`[OmbRouter] Low balance: ${info.balanceUSD}. Fund: ${info.walletAddress}`);
      },
      onInsufficientFunds: (info) => {
        console.error(
          `[OmbRouter] Insufficient funds. Balance: ${info.balanceUSD}, Need: ${info.requiredUSD}`,
        );
        console.error(`[OmbRouter] Need help? Run: ombrouter doctor (or: node dist/cli.js doctor)`);
      },
    });

    const paymentChain = await resolvePaymentChain();
    const displayAddress =
      paymentChain === "solana" && proxy.solanaAddress ? proxy.solanaAddress : wallet.address;
    try {
      const balance = await proxy.balanceMonitor.checkBalance();
      if (balance.isEmpty) {
        console.log(`[OmbRouter] Wallet balance: $0.00 (using FREE model)`);
        console.log(`[OmbRouter] Fund wallet for premium models: ${displayAddress}`);
      } else if (balance.isLow) {
        console.log(`[OmbRouter] Wallet balance: ${balance.balanceUSD} (low)`);
      } else {
        console.log(`[OmbRouter] Wallet balance: ${balance.balanceUSD}`);
      }
      proxy.balanceMonitor.invalidate();
    } catch {
      console.log(`[OmbRouter] Wallet: ${displayAddress} (balance check pending)`);
    }

    console.log(`[OmbRouter] Ready - Ctrl+C to stop`);
  }

  // Handle graceful shutdown
  const shutdown = async (signal: string) => {
    console.log(`\n[OmbRouter] Received ${signal}, shutting down...`);
    try {
      await proxy.close();
      console.log(`[OmbRouter] Proxy closed`);
      process.exit(0);
    } catch (err) {
      console.error(`[OmbRouter] Error during shutdown: ${err}`);
      process.exit(1);
    }
  };

  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("SIGTERM", () => shutdown("SIGTERM"));

  // Keep process alive
  await new Promise(() => {});
}

main().catch((err) => {
  console.error(`[OmbRouter] Fatal error: ${err.message}`);
  console.error(`[OmbRouter] Need help? Run: ombrouter doctor (or: node dist/cli.js doctor)`);
  process.exit(1);
});
